### ISSUE TITLE
Add cors middleware to lumen

### ISSUE THREAD

**Issue by mafeka** [rhein-main-swingtime/eventserver-lumen-php#5]

**Comment by ewerybody** [comment]
was macht dis?

**Comment by mafeka** [comment]
CORS oder die Middleware? :)

Im Prinzip sind CORS Header die einem ausführenden Script signalisieren, von welcher URL aus der Kram abgerufen werden darf und von wo aus nicht. Das soll bestimmte Angriffe (Cross Site Scripting) verhindern.

Das Ding setzt den Header nun erst mal auf '*', macht die API damit komplett public. Sobald wir die Geschichte so richtig in die freie Wildbahn entlassen wollen, sollte das noch mal eingeschränkt werden. Das ist jetzt aber erst mal keine dringende Baustelle und zum Debuggen bisschen einfacher.

Die Middleware ist so ein API Konzept das bei einigen PHP Frameworks gefahren wird. Im Prinzip bekommst du ein Request-Object in dem alle möglichen Daten gekapselt vorhanden sind (Client IP, GET-Params, ...). Das kannst du durch beliebig viele Middlewares pipen, die alles mögliche damit machen. Authentifizierung checken, Header anpassen usw. usf. 

Sobald die Kette von Middlewares durchlaufen ist, kommt das Ding dann beim eigentlichen Controller an, der die Business Logik abfackelt. In unserem Fall dann DB Request und Kram fährt und die entsprechende Response ausliefert.
