### ISSUE TITLE
Event Daten erweitern:

### ISSUE THREAD

**Issue by mafeka** [rhein-main-swingtime/eventserver-lumen-php#8]
Google Calender Events mit Wiederholungen importieren und auf Tabellen verteilen
Table 1: Events
Table 2: Occurences

**Comment by ewerybody** [comment]
Vielleicht können wir die Tage ma wieder nen Abend machen wo du mir das ma im Detail zeigst wie man die API amend benutzt und wie man das angeht alles :)

**Comment by mafeka** [comment]
Happy X-Mas :)

Auf jeden! Lass uns das machen. Ist auch viel zu tun 💪
